settings:
  title: 'Info Agents - Tango Down Checker'
  url: 'https://misinformationgrinder.tk/' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'Not All Systems Operational'
  notAllmonitorsOperational: 'All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: Kremlin
    name: Kremlin
    url: http://en.kremlin.ru/
    method: GET
    expectStatus: 200

  - id: MinistryDefence
    name: Ministry of Defence of the Russian federation
    url: http://eng.mil.ru
    method: GET
    expectStatus: 200

  - id: RussiaGoverment 
    name: Russian Goverment
    url: http://government.ru
    method: GET
    expectStatus: 200

  - id: RussinDefenceExport
    name: Rosoboronexport
    url: http://roe.ru
    method: GET
    expectStatus: 200

  - id: Tass
    name: TASS Russian Agency ( Propaganda Army )
    url: http://en.tass.ru
    method: GET
    expectStatus: 200

  - id: Duma
    name: State Duma
    url: http://duma.gov.ru
    method: GET
    expectStatus: 200

  - id: CentralBank
    name: Russia Central Bank
    url: http://www.cbr.ru
    method: GET
    expectStatus: 200

  - id: SberkBank
    name: SbearBank
    url: http://www.sberbank.ru
    method: GET
    expectStatus: 200
