settings:
  title: 'Info Agents - Tango Down Checker'
  url: 'https://misinformationgrinder.tk/' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Some tango downs are being noticed'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Tango Down - Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: Kremlin
    name: Kremlin
    url: http://en.kremlin.ru/
    method: GET
    expectStatus: 200

  - id: MinistryDefence
    name: Ministry of Defence of the Russian federation
    url: http://eng.mil.ru
    method: GET
    expectStatus: 200

  - id: RussiaGoverment 
    name: Russian Goverment
    url: http://google.com
    method: GET
    expectStatus: 200

  - id: RussinDefenceExport
    name: Rosoboronexport
    url: http://roe.ru
    method: GET
    expectStatus: 200

