# This is a basic workflow to help you get started with Actions

name: domain_checker

# Controls when the workflow will run
#on:
#  schedule:
#      - cron: "0 * * * *" #run every hour

on:
  push:
    branches:
      - main
  repository_dispatch:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Delete file 
        run: rm -f sites.txt
      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v4
        with:
         python-version: 3.8 #install the python needed
      - name: install pip
        run: pip install requests
      - name: execute py script 
        run: python monitor.py
        env:
          key: ${{ secrets.key }}
